# Generated by Django 2.2.13 on 2020-08-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitydonation', '0003_auto_20200725_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
