# Generated by Django 2.2.13 on 2020-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitydonation', '0005_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
